### ISSUE TITLE
Stalker doesn't take ident into account when doing queries

### ISSUE THREAD

**Issue by haaja** [symkat/Stalker#1]
First of all thanks for the great script. :)

Secondly, I've noticed that stalker.pl does take idents into account while saving data into db. However when doing queries, idents are not used to filter results. This problem surfaces when multiple people runs irc client from a same server. Doing whois query for one of the persons will result getting results for all of the persons with same hostname.

I made a small patch with a partial fix (https://haaja.kapsi.fi/stalker/). The problem still occurs when using binded command nick_lookup. Since I haven't done irssi scripting that much and rarely use that command anyways, I'm not sure how to fix that without modifying the script too much.

**Comment by Laurelai** [comment]
I also have this issue, some servers completely mask the host with a standard mask and the script thinks everyone is everyone else.

**Comment by haaja** [comment]
The patch above did fix the issue except when using the nick_lookup. I don't know if the patch applies to the current version of Stalker at all and I don't really bother trying either because I've since changed my IRC client to weechat.

**Comment by IsaacG** [comment]
Commit 55ef58fd77354e736165 allows you to create "guest" hosts which allow you to set specific hosts as not identifying of a person.

https://github.com/symkat/Stalker/commit/55ef58fd77354e73616593097acda957dfc5b451
