### ISSUE TITLE
Can't load stalker.pl

### ISSUE THREAD

**Issue by eerie** [symkat/Stalker#14]
I've installed DBI.pm and DBD-sqlite Perl modules, but trying /script load stalker.pl it says:
21:09 -!- Irssi: Error in script stalker:
21:09 DBD::SQLite::st execute failed: called with 1 bind variables when 0 are needed at ~/.irssi/scripts/stalker.pl line 170.

**Comment by symkat** [comment]
Sometimes things go wonky when you try to load the script before those are fully installed, as a first step try to delete the nicks.db flle (by default ~/.irssi/nicks.db )

**Comment by eerie** [comment]
Thanks, now it loads.
