### ISSUE TITLE
stalker.pl issue DBD::SQLite::db prepare failed: no such table:

### ISSUE THREAD

**Issue by ghost** [symkat/Stalker#2]
14:46:23  DBD::SQLite::db prepare failed: no such table: records at /home/radius/.irssi/scripts/stalker.pl line 128.

is there something i'm missing ? can you please provide some help getting this script loaded for me please and thank you!

Anthony
(radius)

**Comment by symkat** [comment]
Hi Anthony,

This happens when the script is loading and DBI exists, but DBD::SQLite doesn't, you then installed the DBD and reran it.  Try deleting .irssi/nicks.db and reload the script.  I'll add logic to prevent this in the future (or at least provide a more friendly error) by the weekend.

**Comment by ghost** [comment]
thanks that got it working ...

**Comment by alextes** [comment]
Just ran into this, same error but at 169. Thanks for the fix, a nicer error message would've helped ;] Took a short while to find this because it was closed.
