### ISSUE TITLE
Performance could be improved with indexes

### ISSUE THREAD

**Issue by PetteriAimonen** [symkat/Stalker#4]
Stalker.pl is sometimes a bit slow when there are many records in the database.

Adding some indexes to the database helps a lot. I have done this manually but the commands could be integrated to the script:

```
sqlite3 ~/.irssi/nicks.db
CREATE INDEX index1 ON records (nick);
CREATE INDEX index2 ON records (host);
```

**Comment by IsaacG** [comment]
Added with the latest commit (2012-03-27)
Hopefully nothing breaks and this improves performance!
Thank you for the tip.

**Comment by IsaacG** [comment]
Indices added with https://github.com/symkat/Stalker/commit/92358da4ce3639f452bd8a5482e6ebbba81ba3df
