### ISSUE TITLE
Request host lookup by nick

### ISSUE THREAD

**Issue by brinskoj** [symkat/Stalker#6]
Would be a great feature to be able to query stalker by nick and return all hosts associated with that nick.

**Comment by symkat** [comment]
There are two commands added by this plugin:

`/host_lookup` takes a hostname as an argument and returns a list of nicknames which have used that host.

`/nick_lookup` takes a nickname as an argument and returns a list of the hostnames which have been used by that nickname.  (This seems to be the feature you're looking for)

If either of this aren't working for you please open a new ticket.

**Comment by symkat** [comment]
I was wrong, it used to do this but was changed to only returning the nick names.

**Comment by IsaacG** [comment]
Implemented with https://github.com/symkat/Stalker/commit/d99cc6629885dfc1b43020d01774c62c30811aa0 (version 0.76)
